from __future__ import annotations

from collections import Counter
from pathlib import Path

from macro_sage.config import load_inventory
from macro_sage.files import write_text_atomic
from macro_sage.models import Participation, SourceDefinition, SourceInventory, SourceKind


def _safe(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _links(source: SourceDefinition) -> str:
    return (
        f"[Feed]({source.feed_url}) · [Home]({source.homepage_url})"
        if source.homepage_url
        else f"[Feed]({source.feed_url})"
    )


def _source_table(sources: list[SourceDefinition]) -> list[str]:
    lines = [
        "| ID | Source | Status | Publication frequency | Links | Evidence / coverage | "
        "Acquisition | What it is | Why I need it |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for source in sources:
        coverage = (
            f"{source.evidence_tier.value}; {', '.join(source.geographies)}; "
            f"{', '.join(source.asset_classes)}"
        )
        cadence = f"{source.cadence_basis.value}: {source.cadence}"
        status = source.validation_status.value
        if source.last_validation_date:
            status += f" ({source.last_validation_date})"
        if source.validation_note:
            status += f": {source.validation_note}"
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{source.id}`",
                    _safe(source.name),
                    _safe(status),
                    _safe(cadence),
                    _links(source),
                    _safe(coverage),
                    source.acquisition_mode.value,
                    _safe(source.description),
                    _safe(source.rationale),
                )
            )
            + " |"
        )
    return lines


def render_catalog(inventory: SourceInventory) -> str:
    defaults = [
        source
        for source in inventory.sources
        if source.participation is Participation.DEFAULT
    ]
    optional = [
        source
        for source in inventory.sources
        if source.participation is Participation.OPTIONAL
    ]
    unavailable = [
        source
        for source in inventory.sources
        if source.participation is Participation.UNAVAILABLE
    ]
    lines = [
        "# Macro Sage source catalog",
        "",
        "Generated from `config/sources.toml`; do not edit this file by hand.",
        "",
        "Cadence prefixes are **observed**, **implicit** (publisher schedule), or "
        "**expected** (event-driven expectation). The inventory also carries normal "
        "publication gaps, active weekdays, evidence tier, geography, topics, asset "
        "classes, acquisition contract, priority, critical coverage role, scan depth, "
        "daily acquisition limit, health-failure threshold, language, validation "
        "status and owner. Synthesis has no per-source or per-publisher hard cap.",
        "",
        "## Default text sources",
        "",
        *_source_table([source for source in defaults if source.kind is SourceKind.ARTICLE]),
        "",
        "## Optional audio sources",
        "",
        "These feeds participate only when podcasts are explicitly enabled.",
        "",
        *_source_table([source for source in optional if source.kind is SourceKind.PODCAST]),
        "",
        "## Would be good to have, but these don't work",
        "",
        "Unavailable configured sources and candidates are never hit by the daily run.",
        "",
    ]
    if unavailable:
        lines.extend(
            [
                "### Configured unavailable sources",
                "",
                "| ID | Source | Links | Why I need it | Exact problem | Last validation |",
                "|---|---|---|---|---|---|",
            ]
        )
        for source in unavailable:
            lines.append(
                f"| `{source.id}` | {_safe(source.name)} | {_links(source)} | "
                f"{_safe(source.rationale)} | {_safe(source.unavailable_reason or '')} | "
                f"{source.last_validation_date or 'not recorded'} |"
            )
        lines.append("")
    lines.extend(
        [
            "### Candidate registry",
            "",
            "| ID | Source | Expected frequency | Why I need it | Attempted endpoints | "
            "Exact failure / constraint | Last attempt | Next review |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )
    for candidate in inventory.candidates:
        endpoints = "<br>".join(
            f"[endpoint]({endpoint})" for endpoint in candidate.attempted_endpoints
        )
        problem = f"{candidate.precise_failure} Constraint: {candidate.constraint}"
        lines.append(
            f"| `{candidate.id}` | [{_safe(candidate.name)}]({candidate.homepage_url}) | "
            f"{candidate.cadence_basis.value}: {_safe(candidate.expected_cadence)} | "
            f"{_safe(candidate.rationale)} | {endpoints} | {_safe(problem)} | "
            f"{candidate.last_attempt_date} | {candidate.next_review_date} |"
        )
    return "\n".join(lines).rstrip() + "\n"


def render_coverage_matrix(inventory: SourceInventory) -> str:
    participating = [
        source
        for source in inventory.sources
        if source.participation in {Participation.DEFAULT, Participation.OPTIONAL}
    ]
    dimensions = {
        "Participation": Counter(source.participation.value for source in participating),
        "Kind": Counter(source.kind.value for source in participating),
        "Evidence tier": Counter(source.evidence_tier.value for source in participating),
        "Language": Counter(source.language for source in participating),
        "Cadence basis": Counter(source.cadence_basis.value for source in participating),
        "Acquisition": Counter(source.acquisition_mode.value for source in participating),
        "Geography": Counter(value for source in participating for value in source.geographies),
        "Topic": Counter(value for source in participating for value in source.topics),
        "Asset class": Counter(
            value for source in participating for value in source.asset_classes
        ),
    }
    lines = [
        "# Source coverage matrix",
        "",
        "Generated from `config/sources.toml`.",
        "",
        "The initial corpus-balance benchmark is 2026-08-25: 13 collected documents, "
        "of which nine came from ING and Saxo.",
        "",
    ]
    for label, counts in dimensions.items():
        lines.extend((f"## {label}", "", "| Value | Sources |", "|---|---:|"))
        lines.extend(f"| `{value}` | {count} |" for value, count in sorted(counts.items()))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_catalog(
    config: Path,
    catalog: Path,
    coverage: Path,
    *,
    check: bool = False,
) -> None:
    inventory = load_inventory(config)
    outputs = {
        catalog: render_catalog(inventory),
        coverage: render_coverage_matrix(inventory),
    }
    for path, expected in outputs.items():
        if check:
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != expected:
                raise SystemExit(f"{path} is stale; run scripts/generate_source_catalog.py")
        else:
            write_text_atomic(path, expected)
